name: "Release"
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  Build-Publish:
    name: Build-Publish
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]') && startsWith(github.event.head_commit.message, '[release]') && github.repository == 'subquery/ui-library'"
    runs-on: ubuntu-latest
    steps:
      #Check out
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'

    #Identify changes
      - uses: marceloprado/has-changed-path@v1
        id: changed
        with:
            paths: package.json

      - run: yarn

      - name: build
        run: yarn build
      #Publish to npm
      - uses: JS-DevTools/npm-publish@v1
        name: Publish
        if: steps.changed.outputs.changed == 'true'
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: latest
          access: public